### ISSUE TITLE
Fix bug in `remote-user-storage-provider` with ResteasyClientBuilderImpl

### ISSUE THREAD

**Issue by artshishkin** [artshishkin/art-campbell-cqrs-microservices#35]
Logs
```                                                        
2022-08-18 12:28:21.031  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 2022-08-18 09:28:21,027 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Uncaught server error: java.lang.NoClassDefFoundError: org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl
2022-08-18 12:28:21.031  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at net.shyshkin.study.cqrs.user.storage.provider.RemoteUserStorageProviderFactory.buildHttpClient(RemoteUserStorageProviderFactory.java:25)
2022-08-18 12:28:21.031  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at net.shyshkin.study.cqrs.user.storage.provider.RemoteUserStorageProviderFactory.create(RemoteUserStorageProviderFactory.java:16)
2022-08-18 12:28:21.031  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at net.shyshkin.study.cqrs.user.storage.provider.RemoteUserStorageProviderFactory.create(RemoteUserStorageProviderFactory.java:9)
2022-08-18 12:28:21.031  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.storage.AbstractStorageManager.getStorageProviderInstance(AbstractStorageManager.java:229)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.storage.AbstractStorageManager.lambda$getEnabledStorageProviders$0(AbstractStorageManager.java:98)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:503)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.storage.UserStorageManager.getUserByUsername(UserStorageManager.java:334)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.models.cache.infinispan.UserCacheSession.getUserByUsername(UserCacheSession.java:268)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.models.utils.KeycloakModelUtils.findUserByNameOrEmail(KeycloakModelUtils.java:236)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.authentication.authenticators.directgrant.ValidateUsername.authenticate(ValidateUsername.java:64)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:446)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:250)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1017)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.resourceOwnerPasswordCredentialsGrant(TokenEndpoint.java:605)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:202)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
2022-08-18 12:28:21.032  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: Caused by: java.lang.ClassNotFoundException: org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:107)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:57)
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 	... 75 more
2022-08-18 12:28:21.033  INFO 23476 --- [ream--434489625] o.t.containers.DockerComposeContainer    : [/gh9p6puhnncw_oauth20-server_1] STDOUT: 

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error: "{"error":"unknown_error"}"

	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:100)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:170)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:468)
	at net.shyshkin.study.cqrs.user.query.api.commontest.AbstractDockerComposeTest.getJwtAccessToken(AbstractDockerComposeTest.java:83)
	at net.shyshkin.study.cqrs.user.query.api.UserQueryApiApplicationTest.getTokenByUsername_andGetUserById(UserQueryApiApplicationTest.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by artshishkin** [comment]
UserQueryApiApplicationTest

**Comment by artshishkin** [comment]
- [ ] Write tests to cover this case
